version: '3.1'
services:
  stats-server:
    container_name: stats-server
    build: stats-server/server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/java-explore-with-me
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123
      #- TZ=Europe/Moscow

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=java-explore-with-me
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123
      #- TZ=Europe/Moscow

  ewm-service:
    container_name: ewm-server
    build: ewm-server
    ports:
      - "8080:8080"

  #ewm-db:
  #  image: postgres:14-alpine
