DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS compilations CASCADE;
DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS requests CASCADE;
DROP TABLE IF EXISTS compilations_events CASCADE;
DROP TABLE IF EXISTS comments CASCADE;

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(254) NOT NULL UNIQUE,
    name varchar(250) NOT NULL
);

CREATE TABLE IF NOT EXISTS categories (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS events (
    annotation varchar(2000) NOT NULL,
    category_id INTEGER REFERENCES categories(id),
    confirmed_Requests INTEGER,
    created_On timestamp without time zone,
    description varchar(7000) NOT NULL,
    event_Date timestamp without time zone,
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    initiator_id INTEGER REFERENCES users(id),
    loc_Lat real,
    loc_Lon real,
    paid boolean,
    participant_Limit INTEGER,
    published_On timestamp without time zone,
    request_Moderation boolean,
    state varchar(50) NOT NULL,
    title varchar(120) NOT NULL,
    views INTEGER
);

CREATE TABLE IF NOT EXISTS requests (
    created timestamp without time zone,
    event INTEGER REFERENCES events(id),
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requester INTEGER REFERENCES users(id),
    status varchar(50) NOT NULL,
    unique(event, requester) --не допускаются повторные запросы
);

CREATE TABLE IF NOT EXISTS compilations (
    events_id INTEGER REFERENCES events(id),
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pinned boolean,
    title varchar(500)
);

CREATE TABLE IF NOT EXISTS compilations_events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id INTEGER REFERENCES events(id),
    compilation_id INTEGER REFERENCES compilations(id)
    );

CREATE TABLE IF NOT EXISTS comments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text varchar(1000) NOT NULL,
    event_id INTEGER NOT NULL REFERENCES events(id),
    author_id INTEGER NOT NULL REFERENCES users(id),
    created timestamp without time zone
    );
